ALTER TABLE app_user
    ADD COLUMN first_name  VARCHAR(100),
    ADD COLUMN middle_name VARCHAR(100),
    ADD COLUMN last_name   VARCHAR(100),
    ADD COLUMN user_type   VARCHAR(20) NOT NULL DEFAULT 'INTERNAL';
